---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-urlredirector-av0-de-v1beta1-redirect
  failurePolicy: Fail
  name: mredirect.kb.io
  rules:
  - apiGroups:
    - urlredirector.av0.de
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redirects
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-urlredirector-av0-de-v1beta1-redirect
  failurePolicy: Fail
  name: vredirect.kb.io
  rules:
  - apiGroups:
    - urlredirector.av0.de
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redirects
  sideEffects: None
