# permissions for end users to view redirects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redirect-viewer-role
rules:
  - apiGroups:
      - urlshortener.av0.de
      - networking.k8s.io
    resources:
      - redirects
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - urlshortener.av0.de
    resources:
      - redirects/status
    verbs:
      - get
