apiVersion: urlredirector.av0.de/v1beta1
kind: Redirect
metadata:
  name: redirect-sample
spec:
  source: cedric-kienzler.de
  target: cedi.dev
  http_redirect: 301

---
apiVersion: urlredirector.av0.de/v1beta1
kind: Redirect
metadata:
  name: redirect-sample2
spec:
  source: cedric-kienzler.de
  target: cedi.dev

---
apiVersion: urlredirector.av0.de/v1beta1
kind: Redirect
metadata:
  name: redirect-sample3
spec:
  source: cedric-kienzler.de
  target: cedi.dev
  http_redirect: 404

---
apiVersion: urlredirector.av0.de/v1beta1
kind: Redirect
metadata:
  name: redirect-sample4
spec:
  source: cedric-kienzler.de
  target: cedi.dev
  http_redirect: 300
