# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
  - bases/urlshortener-controller.clusterserviceversion.yaml
  - ../default
  - ../samples
  - ../scorecard

# [WEBHOOK] To enable webhooks, uncomment all the sections with [WEBHOOK] prefix.
# Do NOT uncomment sections with prefix [CERTMANAGER], as OLM does not support cert-manager.
# These patches remove the unnecessary "cert" volume and its manager container volumeMount.
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: manager-role
    patch: |-
      - op: add
        path: /rules/0/resources/-
        value: ingresses
      - op: add
        path: /rules/0/apiGroups/-
        value: networking.k8s.io
