name: Go

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: make test
